version: '2'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-https-proxy
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.key:/etc/nginx/ssl/cert.key
      - ./ssl/cert.pem:/etc/nginx/ssl/cert.pem
    ports:
      - 443:443